# Generated by Django 3.1.1 on 2023-02-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=200)),
                ('Image', models.ImageField(default='https://cdn.wpmeducation.com/53544f/97c04745fa/default.jpg', upload_to='')),
            ],
        ),
    ]
