# Generated by Django 3.1.1 on 2023-02-12 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cetus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModelNo', models.CharField(max_length=200)),
                ('ProductImage', models.ImageField(default='https://cdn.wpmeducation.com/53544f/97c04745fa/default.jpg', upload_to='')),
                ('Category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='cetus.category')),
            ],
        ),
    ]
