# Generated by Django 3.1.1 on 2023-02-12 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cetus', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
