# Generated by Django 3.1.1 on 2023-02-18 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cetus', '0006_auto_20230218_1640'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
