# Generated by Django 3.1.1 on 2023-02-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cetus', '0008_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirnment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Company', models.CharField(max_length=200)),
                ('Designation', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('Pincode', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=200)),
                ('Country', models.CharField(max_length=200)),
                ('Mobile', models.CharField(max_length=200)),
                ('Telephone', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Modelno', models.CharField(max_length=200)),
            ],
        ),
    ]
