# Generated by Django 3.1.1 on 2023-03-12 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cetus', '0012_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirnment',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
